#
# Package name
#

NAME=R3Utils



#
# List of source files
#

CCSRCS=$(NAME).cpp \
    R3SurfelViewer.cpp \
    R3SurfelSegmenter.cpp \
    R3SurfelClassifier.cpp \
    R3SurfelLabeler.cpp \
    R3SurfelLabelerCommand.cpp \
    R3OrientedBoxManipulator.cpp \
    R3Segmentation.cpp



#
# Dependencies
#

PKG_DEPENDENCIES = R3Surfels R3Graphics R3Shapes R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs




