#
# Package name
#

NAME=R3Utils



#
# List of source files
#

CCSRCS=$(NAME).cpp \
    R3Segmentation.cpp



#
# Dependencies
#

PKG_DEPENDENCIES = R3Shapes R2Shapes RNBasics



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs




