#
# Package name and list of source files.
#

NAME=RNNets
CCSRCS=$(NAME).cpp \
	RNTcp.cpp RNUdp.cpp RNIp.cpp \
	RNModem.cpp \
	RNNet.cpp



#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs



