#
# Application name and list of source files.
#

NAME=sfldetect
CCSRCS=$(NAME).cpp \
  parse.cpp assignment.cpp \
  detection.cpp segmentation.cpp \
  label.cpp model.cpp \
  pointset.cpp point.cpp \
  align.cpp descriptor.cpp


#
# Dependency libraries
#

PKG_LIBS=-lGSV -lR3Surfels -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng -lfft

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


