#
# Package name
#

NAME=MP



#
# List of source files
#

CCSRCS=MP.cpp \
    MPHouse.cpp \
    MPLevel.cpp \
    MPPortal.cpp \
    MPRegion.cpp \
    MPSurface.cpp \
    MPVertex.cpp \
    MPCategory.cpp \
    MPObject.cpp \
    MPSegment.cpp \
    MPPanorama.cpp \
    MPImage.cpp \
    MPUtils.cpp



#
# Dependencies
#

PKG_DEPENDENCIES = RGBD R3Shapes R2Shapes RNBasics jpeg png



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs







