#
# Package name 
#

NAME=GSV



#
# List of source files
#

CCSRCS=$(NAME).cpp \
  GSVScene.cpp \
  GSVRun.cpp \
  GSVSegment.cpp \
  GSVCamera.cpp \
  GSVPanorama.cpp \
  GSVImage.cpp \
  GSVTapestry.cpp \
  GSVLaser.cpp \
  GSVSurvey.cpp \
  GSVScan.cpp \
  GSVScanline.cpp \
  GSVMesh.cpp \
  GSVPose.cpp \
  GSVPoint.cpp


#
# Dependencies
#

DEPENDENCIES=*.h ../R3Shapes/*.h ../R2Shapes/*.h ../RNBasics/*.h



#
# PKG makefile
#

include ../../makefiles/Makefile.pkgs


