#
# Application name and list of source files.
#

NAME=mshsegment
CCSRCS=$(NAME).cpp 



#
# Dependency libraries
#

PKG_LIBS=-lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng -lgco



#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


