#
# Application name and list of source files.
#

NAME=conf2sfl
CCSRCS=$(NAME).cpp 


#
# Pkg libraries
#

PKG_LIBS=-lRGBD -lR3Utils -lR3Surfels -lR3Shapes -lR2Shapes -lRNMath -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


